---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebsvol
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: "vol-0be6776cc6e164cac"
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myebsvolclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
