# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vprodb
#   labels:
#     app: vprodb
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: vprodb
#   template:
#      metadata:
#        labels:
#          app: vprodb
#      spec:
#         containers:
#          - name: vprodb
#            image: vikashashoke/vprofiledb:latest
#            volumeMounts:
#              - mountPath: /var/lib/mysql
#                name: vpro-db-data
#            ports:
#              - containerPort: 3306
#                name: vprodb-port
#            env:
#              - name: MYSQL_ROOT_PASSWORD
#                valueFrom:
#                  secretKeyRef:
#                     name: app-secret
#                     key: db-pass
#         volumes:
#           - name: vpro-db-data
#             persistentVolumeClaim:
#               claimName: myebsvolclaim

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vprodb
#   labels:
#     app: vprodb
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: vprodb
#   template:
#      metadata:
#        labels:
#          app: vprodb
#      spec:
#         containers:
#          - name: vprodb
#            image: vikashashoke/vprofiledb:latest
#            ports:
#              - containerPort: 3306
#                name: vprodb-port
#            env:
#              - name: MYSQL_ROOT_PASSWORD
#                valueFrom:
#                  secretKeyRef:
#                     name: app-secret
#                     key: db-pass
                    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
     metadata:
       labels:
         app: vprodb
     spec:
        containers:
         - name: vprodb
           image: vikashashoke/vprofiledb:latest
           volumeMounts:
             - name:  vpro-db-data
               mountPath:  /avr/lib/mysql
           ports:
             - containerPort: 3306
               name: vprodb-port
           env:
             - name: MYSQL_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
                    name: app-secret
                    key: db-pass
        nodeSelector:
          topology.kubernetes.io/zone: us-east-1a
        volumes:
          - name:  vpro-db-data
            awsElasticBlockStore:
              volumeID: vol-01444f5c390de81a7
              fsType: ext4


--- 
apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  selector:
     app: vprodb
  ports:
    - port: 3306
      protocol: TCP
      targetPort: vprodb-port
